version: 2

models:
  - name: fact_climate_population
    description: "The final optimized fact table."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - record_date

    columns:
      - name: country_code
        tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 3

      - name: record_date
        tests:
          - not_null

      - name: annual_avg_temp
        tests:
          - not_null

      - name: population
        tests:
          - not_null

  - name: fact_temp_increase_ranking
    description: "Summary table showing the total temperature change per country."
    columns:
      - name: country
        description: "Standardized country name."
        tests:
          - unique
          - not_null

      - name: temp_start_year
        description: "Average temperature in the project start year."
        tests:
          - not_null

      - name: temp_end_year
        description: "Average temperature in the expected end year."
        tests:
          - not_null

      - name: total_increase
        description: "The delta (End Temp - Start Temp)."
        tests:
          - not_null